# Generated by Django 4.2 on 2023-05-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_alter_course_course_discriminator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='video_url',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
