# Generated by Django 4.2.1 on 2023-05-07 16:44

import VidSellApp.validat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VidSellApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video/%y', validators=[VidSellApp.validat.file_size]),
        ),
    ]
