# Generated by Django 3.2.18 on 2023-05-08 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VidSellApp', '0002_alter_video_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title_name', models.CharField(max_length=200)),
                ('video_description_name', models.CharField(max_length=200)),
                ('price_name', models.PositiveIntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VidSellApp.video')),
            ],
        ),
    ]
